// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jowibaodounccqgpieuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvd2liYW9kb3VuY2NxZ3BpZXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NzU0MzQsImV4cCI6MjA4MzE1MTQzNH0.VfUWcinlV0BN-BXVXEQWj4623kpXNC2D1pO4uwmOEiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);